# Generated by Django 4.0 on 2024-06-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item2_1_message', models.TextField()),
                ('item2_1_reference', models.TextField()),
                ('item2_1_document', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='GoToChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reference', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KazahstanCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1_2_message', models.TextField()),
                ('item1_2_reference', models.TextField()),
                ('item1_2_document', models.FileField(upload_to='documents')),
                ('item1_3_message', models.TextField()),
                ('item1_3_reference', models.TextField()),
                ('item1_3_document', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='OpenAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item3_1_message', models.TextField()),
                ('item3_1_reference', models.TextField()),
                ('item3_1_document', models.FileField(upload_to='documents')),
                ('item3_2_message', models.TextField()),
                ('item3_2_reference', models.TextField()),
                ('item3_2_document', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='USDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reference', models.TextField()),
            ],
        ),
    ]
