# Generated by Django 4.0 on 2024-06-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposited',
            options={'verbose_name': 'Пункт Депозит'},
        ),
        migrations.AlterModelOptions(
            name='gotochat',
            options={'verbose_name': 'Пункт Переход в чат'},
        ),
        migrations.AlterModelOptions(
            name='kazahstancart',
            options={'verbose_name': 'Пункт Карта Казахстана'},
        ),
        migrations.AlterModelOptions(
            name='openaccount',
            options={'verbose_name': 'Пункт Открытие счетов'},
        ),
        migrations.AlterModelOptions(
            name='usdt',
            options={'verbose_name': 'Пункт Перестановка USDT'},
        ),
        migrations.AlterField(
            model_name='deposited',
            name='item2_1_document',
            field=models.FileField(upload_to='documents', verbose_name='Загрузка документа для пункта 2.1'),
        ),
        migrations.AlterField(
            model_name='deposited',
            name='item2_1_message',
            field=models.TextField(verbose_name='Текст сообщения для пункта 2.1'),
        ),
        migrations.AlterField(
            model_name='deposited',
            name='item2_1_reference',
            field=models.TextField(verbose_name='Ссылка для пункта 2.1'),
        ),
        migrations.AlterField(
            model_name='gotochat',
            name='message',
            field=models.TextField(verbose_name='Текст сообщения для пункта 4'),
        ),
        migrations.AlterField(
            model_name='gotochat',
            name='reference',
            field=models.TextField(verbose_name='Ссылка для пункта 4'),
        ),
        migrations.AlterField(
            model_name='kazahstancart',
            name='item1_2_document',
            field=models.FileField(upload_to='documents', verbose_name='Загрузка документа для пункта 1.2'),
        ),
        migrations.AlterField(
            model_name='kazahstancart',
            name='item1_2_message',
            field=models.TextField(verbose_name='Текст сообщения для пункта 1.2'),
        ),
        migrations.AlterField(
            model_name='kazahstancart',
            name='item1_2_reference',
            field=models.TextField(verbose_name='Ссылка для пунка 1.2'),
        ),
        migrations.AlterField(
            model_name='kazahstancart',
            name='item1_3_document',
            field=models.FileField(upload_to='documents', verbose_name='Загрузка документа для пункта 1.3'),
        ),
        migrations.AlterField(
            model_name='kazahstancart',
            name='item1_3_message',
            field=models.TextField(verbose_name='Текст сообщения для пункта 1.3'),
        ),
        migrations.AlterField(
            model_name='kazahstancart',
            name='item1_3_reference',
            field=models.TextField(verbose_name='Ссылка для пунка 1.3'),
        ),
        migrations.AlterField(
            model_name='openaccount',
            name='item3_1_document',
            field=models.FileField(upload_to='documents', verbose_name='Загрузка документа для пункта 3.1'),
        ),
        migrations.AlterField(
            model_name='openaccount',
            name='item3_1_message',
            field=models.TextField(verbose_name='Текст сообщения для пункта 3.1'),
        ),
        migrations.AlterField(
            model_name='openaccount',
            name='item3_1_reference',
            field=models.TextField(verbose_name='Ссылка для пункта 3.1'),
        ),
        migrations.AlterField(
            model_name='openaccount',
            name='item3_2_document',
            field=models.FileField(upload_to='documents', verbose_name='Загрузка документа для пункта 3.2'),
        ),
        migrations.AlterField(
            model_name='openaccount',
            name='item3_2_message',
            field=models.TextField(verbose_name='Текст сообщения для пункта 3.2'),
        ),
        migrations.AlterField(
            model_name='openaccount',
            name='item3_2_reference',
            field=models.TextField(verbose_name='Ссылка для пункта 3.2'),
        ),
        migrations.AlterField(
            model_name='usdt',
            name='message',
            field=models.TextField(verbose_name='Текст сообщения для пункта 5'),
        ),
        migrations.AlterField(
            model_name='usdt',
            name='reference',
            field=models.TextField(verbose_name='Ссылка для пункта 5'),
        ),
    ]
