# Generated by Django 4.0 on 2024-06-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_deposited_options_alter_gotochat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposited',
            options={'verbose_name': 'Пункт Депозит', 'verbose_name_plural': 'Пункт Депозит'},
        ),
        migrations.AlterModelOptions(
            name='gotochat',
            options={'verbose_name': 'Пункт Переход в чат', 'verbose_name_plural': 'Пункт Переход в чат'},
        ),
        migrations.AlterModelOptions(
            name='kazahstancart',
            options={'verbose_name': 'Пункт Карта Казахстана', 'verbose_name_plural': 'Пункт Карта Казахстана'},
        ),
        migrations.AlterModelOptions(
            name='openaccount',
            options={'verbose_name': 'Пункт Открытие счетов', 'verbose_name_plural': 'Пункт Открытие счетов'},
        ),
        migrations.AlterModelOptions(
            name='usdt',
            options={'verbose_name': 'Пункт Перестановка USDT', 'verbose_name_plural': 'Пункт Перестановка USDT'},
        ),
    ]
