services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POST_DB}
      - POSTGRES_USER=${POST_USER}
      - POSTGRES_PASSWORD=${POST_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  db-data:

networks:
  mynetwork:
    driver: bridge
