networks:
  mynetwork:
    driver: bridge

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POST_DB}
      - POSTGRES_USER=${POST_USER}
      - POSTGRES_PASSWORD=${POST_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=admin.settings
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./static:/app/static
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  static:
  postgres_data: